Added src folder; moved all ".h" and ".cpp" files to the src folder; …
ProgProgrammer/tanks2 pull request #2
Opened 2022-06-22 20:11 UTC by ProgProgrammer

…changed the Tanks2 project code.

2022-07-05 07:42 UTC, marleeeeeey reviewed
TankUML.drawio - обнови это файл с последними заданиями, у тебя он старый. Нужно просто перезалить

2022-07-05 09:40 UTC, marleeeeeey requested changes

2022-07-05 09:40 UTC, marleeeeeey commented on Tanks2/Tanks2/src/brick.cpp
> +        int elem = (int)cell_num - 48;
магическое число! почему именно 48 тут? Надо название дать осмысленное

2022-07-05 09:40 UTC, marleeeeeey commented on Tanks2/Tanks2/src/levelgenerator.cpp
> +std::vector<std::string> LevelGenerator::getRandomLevel() const
тут ты не совсем понял, что я хотел. Созвонимся, обсудим

2022-07-05 09:40 UTC, marleeeeeey commented on Tanks2/Tanks2/src/levelgenerator.cpp
> +    levels.resize(1);
не надо делать resize. 
нужно делать levels.push_back(current_level)

2022-07-05 09:40 UTC, marleeeeeey commented on Tanks2/Tanks2/src/level.h
> +    using level = std::vector<std::vector<std::string>>;
using Level (с большой буквы, т.к. это тип получается).

2022-07-05 09:40 UTC, marleeeeeey commented on Tanks2/Tanks2/src/level.h
> +    level levels;
std::vector<Level> levels; 

сейчас ты все уровни хранишь в одном уровне - это не правильно

2022-07-05 09:40 UTC, marleeeeeey commented on Tanks2/Tanks2/src/world.cpp
> +            bricks.push_back(new Brick(dx, dy, str_arr[i][a], window, config));
Обсудим этот кусок голосом.

2022-07-05 09:40 UTC, marleeeeeey commented on Tanks2/Tanks2/src/world.cpp
> +    rendering();
Не надо запускать рендеринг вне цикла игрового. Удали это. Обсудим.

2022-07-05 11:16 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/level.h
> +    using level = std::vector<std::vector<std::string>>;
Каким образом? Нельзя указывать название типа таким же как класс.

2022-07-05 11:17 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/level.h
> +    level levels;
А как нужно?

2022-07-05 11:18 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/world.cpp
> +    rendering();
Удалю, но программа от этого работать перестанет.

2022-07-05 13:29 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/brick.cpp
> +        int elem = (int)cell_num - 48;
Исправил.

2022-07-05 13:29 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/level.h
> +    using level = std::vector<std::vector<std::string>>;
Исправил.

2022-07-08 14:44 UTC, marleeeeeey approved these changes

2022-07-08 14:44 UTC, marleeeeeey commented on Tanks2/Tanks2/src/level.h
> +    using level = std::vector<std::vector<std::string>>;
А, я понял. Давай голосом обсудим. Класс тут вообще не нужен

2022-07-08 14:44 UTC, marleeeeeey commented on Tanks2/Tanks2/src/world.cpp
> +    rendering();
на мой взгляд должна работать. Ты же рендеришь в функции mainLoop

2022-07-08 14:44 UTC, marleeeeeey commented on Tanks2/Tanks2/src/level.h
> +    LEVEL levels;
Исправить

2022-07-08 14:44 UTC, marleeeeeey commented on Tanks2/Tanks2/src/levelgenerator.cpp
> +std::vector<std::string> LevelGenerator::getRandomLevel() const
функцию удалить

2022-07-08 14:44 UTC, marleeeeeey commented on Tanks2/Tanks2/src/levelgenerator.cpp
> +void LevelGenerator::readLevelFromFile(const std::string& filename)
Возвращать Levels

2022-07-08 14:44 UTC, marleeeeeey commented on Tanks2/Tanks2/src/random_mover.h
> +__declspec(dllexport) int getRandomIntDll(const int min, const int& max);
Переименуй файл в utils.cpp и utils.h

удалить _declspec(dllexport)

переименовать ее в `getRandomInt`

2022-07-08 14:50 UTC, ProgProgrammer commented
Add support reading levels and generate bricks.

2022-07-08 14:51 UTC, merged