Changed TankUML file to the Tanks2 project
ProgProgrammer/tanks2 pull request #3
Opened 2022-07-08 16:15 UTC by ProgProgrammer

Прошу проверить мой код.

2022-07-11 18:02 UTC, marleeeeeey requested changes

2022-07-11 18:02 UTC, marleeeeeey commented on Tanks2/Tanks2/src/tank.h
> +    bool m_top_rotate = true;
bool m_top_rotate = true;
    bool m_bottom_rotate = false;
    bool m_left_rotate = false;
    bool m_right_rotate = false;
Мне кажется логично заменить на enum Direction с четырмыя

2022-07-11 18:02 UTC, marleeeeeey commented on Tanks2/Tanks2/src/tank.h
> +    int m_width_window;
int m_width_window;
    int m_height_window;
Эти значения не нужно хранить в классе, их всегда можно получить из конфигурации.

2022-07-11 18:02 UTC, marleeeeeey commented on Tanks2/Tanks2/src/tank.h
> +    float m_half_width_tank;
float m_half_width_tank;
    float m_half_height_tank;
Эти значения тоже я бы перенес внутрь функции, где они используются. Зачем они на уровне класса нужны?

2022-07-11 18:02 UTC, marleeeeeey commented on Tanks2/Tanks2/src/tank.h
> +    Tank(int& w, int& h, sf::RenderWindow& window, int& width_window, int& height_window, int& speed_tank);
![image](https://user-images.githubusercontent.com/19382499/178327945-09fa5a84-b2cb-44a2-9d5a-9db640670c80.png)

Передавай конфигурацию, а не кучу параметров!

2022-07-11 18:02 UTC, marleeeeeey commented on Tanks2/Tanks2/src/world.cpp
> +    int width_window = 400;
int width_window = 400;
    int height_window = 200;
Вот эти параметры должы попасть в конфигурацию приложения!
class Config

2022-07-11 18:02 UTC, marleeeeeey commented on Tanks2/Tanks2/src/tank.cpp
>  void Tank::calculate(sf::Event& event)
Логика работы с событиями слишком запутанная, много дублирования. Лучше голосом обсудить.

2022-07-11 18:03 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/tank.h
> +    bool m_top_rotate = true;
Да. Исправлю.

2022-07-11 18:04 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/tank.h
> +    float m_half_width_tank;
Чтобы каждый раз не вычислять по новой. Это экономит ресурсы и код от этого сложнее не становится.

2022-07-11 18:05 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/world.cpp
> +    int width_window = 400;
Ты имеешь в виду файл config.h?
Я тогда и window вынесу в этот файл.

2022-07-11 18:05 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/tank.h
> +    int m_width_window;
Ты имеешь в виду файл config.h?

2022-07-11 18:06 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/tank.cpp
>  void Tank::calculate(sf::Event& event)
Давай голосом. Может завтра?

2022-07-11 18:11 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/tank.h
> +    Tank(int& w, int& h, sf::RenderWindow& window, int& width_window, int& height_window, int& speed_tank);
Сделал.

2022-07-11 18:14 UTC, marleeeeeey commented on Tanks2/Tanks2/src/tank.h
> +    int m_width_window;
Да, а именно класс Config, новый класс не нужно создавать

2022-07-11 18:15 UTC, marleeeeeey commented on Tanks2/Tanks2/src/tank.h
> +    float m_half_width_tank;
Загромождает класс лишней информацией на мой взгляд. Ну хочешь, оставь так

2022-07-11 18:15 UTC, marleeeeeey commented on Tanks2/Tanks2/src/world.cpp
> +    int width_window = 400;
да все так

2022-07-11 18:23 UTC, marleeeeeey commented on Tanks2/Tanks2/src/tank.cpp
>  void Tank::calculate(sf::Event& event)
Давай завтра созвонимся. Как пример, посмотри этот [код](https://github.com/marleeeeeey/CppProjects/blob/master/2019-11-23_0032_ArkanoidSFML/ArkanoidSFML/ArkanoidLib/src/Plate.cpp).

Вот как я анализировал событие
```
    if (event && event.value().type == sf::Event::EventType::KeyPressed
        && event.value().key.code == sf::Keyboard::Key::Left
        && m_plateState != PlateState::MoveLeft)
    {
        m_plateState = PlateState::MoveLeft;
    }
```
Далее я считал смещение `m_offset ` объекта в следующем кадре относительно предыдущего - оно может быть и положительным и отрицательным, в зависимости от направления - у тебя их будет два, потому что вертикальное (вверх и вниз) и горизонтальное (влево и вправо) смещение.
И оно может иметь разное значение - определяющее скорость объекта.
```
    switch (m_plateState)
    {
    case PlateState::Stop:
        if (m_offset > 0)
            m_offset -= absDampingOffset;
        else if (m_offset < 0)
            m_offset += absDampingOffset;
        if (m_offset != 0 && abs(m_offset) < absDampingOffset)
            m_offset = 0;
        break;
    case PlateState::MoveLeft:
        m_offset = -absOffset;
        break;
    case PlateState::MoveRight:
        m_offset = absOffset;
        break;
    }
```
А далее я уже добавлял это значение к координатам объекта
```
void Plate::calcState(std::optional<sf::Event> event, sf::Time elapsedTime)
{
    sf::Vector2f pos01 = state().getPos();
    calculateOffset(event, elapsedTime);
    auto pos = state().getPos();
    pos.x += m_offset;
```
Поразмысли над этим, завтра созвонимся и обсудим голосом.

2022-07-12 10:44 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/world.cpp
> +    int width_window = 400;
Сделал.

2022-07-12 10:45 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/tank.h
> +    int m_width_window;
Сделал.

2022-07-12 10:45 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/tank.h
> +    float m_half_width_tank;
В классе оставил.

2022-07-12 10:45 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/tank.h
> +    bool m_top_rotate = true;
Не смог исправить. Нужен созвон.

2022-07-12 10:45 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/tank.cpp
>  void Tank::calculate(sf::Event& event)
Давай сегодня поразмыслим. Когда созвонимся?

2022-07-12 15:32 UTC, ProgProgrammer commented on Tanks2/Tanks2/src/tank.h
> +    bool m_top_rotate = true;
Готово.

2022-07-12 19:00 UTC, marleeeeeey requested changes

2022-07-12 19:00 UTC, marleeeeeey commented on Tanks2/Tanks2/src/world.cpp
> +        std::this_thread::sleep_for(2ms - elapsed);
2ms
это слишком часто. 500 FPS. Надо вернуть 40ms. Если там будут проблемы с задержками решим через вычисления используя время, я потом объясню как.

2022-07-12 19:02 UTC, marleeeeeey requested changes
![image](https://user-images.githubusercontent.com/19382499/178573667-c3aebb9a-0733-4585-ace7-ac32e4915221.png)
переименуй в `i_drawable.h`

2022-07-14 10:41 UTC, merged